'use client';
import {useEffect,useRef,useState} from 'react';
type Comment={id:number,nickname:string,body:string,created_at:number};
type Turnstile={render:(el:HTMLElement,opts:Record<string,unknown>)=>string,reset:(id:string)=>void,remove:(id:string)=>void};
declare global{interface Window{turnstile?:Turnstile}}
let loader:Promise<void>|undefined;
function loadWidget(){return loader??=(new Promise<void>((resolve,reject)=>{if(window.turnstile){resolve();return}const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.onload=()=>resolve();s.onerror=()=>{loader=undefined;reject(Error('驗證元件載入失敗，請重新整理。'))};document.head.appendChild(s)}))}
export default function Comments({thread}:{thread:string}){
 const [rows,setRows]=useState<Comment[]>([]),[next,setNext]=useState<number|null>(null),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true);
 const [nickname,setNickname]=useState(''),[body,setBody]=useState(''),[token,setToken]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[sending,setSending]=useState(false);
 const mount=useRef<HTMLDivElement>(null),widget=useRef<string|undefined>(undefined),requestId=useRef('');
 async function read(more=false){setLoading(true);setLoadError('');try{const r=await fetch('/api/comments?thread='+encodeURIComponent(thread)+(more&&next?'&before='+next:''));const d=await r.json() as {error?:string,comments:Comment[],next:number|null};if(!r.ok)throw Error(d.error||'無法載入留言');setRows(old=>more?[...old,...d.comments]:d.comments);setNext(d.next)}catch(e){setLoadError(e instanceof Error?e.message:'無法載入留言')}finally{setLoading(false)}}
 useEffect(()=>{void read();let cancelled=false;async function init(){try{const r=await fetch('/api/comments/config');const d=await r.json() as {enabled:boolean,siteKey:string};if(!r.ok||!d.enabled)throw Error('留言服務準備中，請稍後再來。');await loadWidget();if(cancelled||!mount.current)return;widget.current=window.turnstile!.render(mount.current,{sitekey:d.siteKey,action:'comment',theme:'light',size:'flexible',callback:(t:string)=>setToken(t),'expired-callback':()=>setToken(''),'error-callback':()=>{setToken('');setNotice('驗證未完成，請重新整理後再試。')}});setReady(true)}catch(e){if(!cancelled)setNotice(e instanceof Error?e.message:'留言服務暫時無法使用')}}void init();return()=>{cancelled=true;if(widget.current)window.turnstile?.remove(widget.current)}},[thread]);
 async function submit(e:React.FormEvent){e.preventDefault();if(sending||!token)return;setSending(true);setNotice('');requestId.current||=crypto.randomUUID();try{const r=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({thread,nickname,body,token,requestId:requestId.current})});const d=await r.json() as {error?:string,message:string};if(!r.ok)throw Error(d.error||'送出失敗');setNotice(d.message);setBody('');requestId.current=''}catch(e){setNotice(e instanceof Error?e.message:'送出失敗，內容已保留，請重試。')}finally{setSending(false);setToken('');if(widget.current)window.turnstile?.reset(widget.current)}}
 return <section className="section comments" id="comments" aria-labelledby="comments-heading"><h2 id="comments-heading">留言與提問</h2><p>不用註冊。分享你的組裝經驗，或留下想一起解決的問題。留言審核後才會公開。</p><form onSubmit={submit}><label htmlFor="comment-name">暱稱（選填）</label><input id="comment-name" value={nickname} maxLength={40} placeholder="匿名" onChange={e=>setNickname(e.target.value)} disabled={sending}/><label htmlFor="comment-body">留言</label><textarea id="comment-body" value={body} maxLength={2000} required rows={5} onChange={e=>{setBody(e.target.value);requestId.current=''}} disabled={sending}/><p className="meta">{body.length}/2000 字。請勿填寫電話、地址或其他私密資料。</p><div ref={mount}/><button className="button primary" type="submit" disabled={!ready||!token||!body.trim()||sending}>{sending?'送出中…':'送出，等待審核'}</button><p role="status" aria-live="polite">{notice}</p></form><p className="meta">公開只顯示暱稱、內容與時間。本站以每日更換的雜湊識別值限制發文，不儲存原始 IP；Cloudflare 仍會處理連線資料與防垃圾驗證。<a href="https://www.cloudflare.com/privacypolicy/">Cloudflare 隱私政策</a></p><h3>已公開的留言</h3>{loadError?<p role="alert">{loadError} <button className="button" onClick={()=>read()}>重新載入</button></p>:null}{loading&&!rows.length?<p>載入中…</p>:!rows.length&&!loadError?<p className="meta">目前還沒有公開留言，歡迎留下第一個問題。</p>:null}<div>{rows.map(c=><article className="comment" key={c.id}><p><strong>{c.nickname}</strong> <time className="meta" dateTime={new Date(c.created_at*1000).toISOString()}>{new Date(c.created_at*1000).toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei'})}</time></p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{c.body}</p></article>)}</div>{next?<button className="button" onClick={()=>read(true)} disabled={loading}>載入較早留言</button>:null}</section>
}
