export const dynamic = 'force-static';
import type {Metadata} from 'next';
export const metadata:Metadata={title:'重現指南'};
const UP='https://github.com/apirrone/Open_Duck_Mini/blob/b23317a485b3cec7d8417f352478778b3475173c/';
export default function Guide(){return <main id="content"><header className="page-intro"><p className="eyebrow">REPRODUCE / READ → FIT → RECORD</p><h1>從一份清楚的版本開始。</h1><p>這份指南整理我們實際走過的準備與右腿組裝過程。全機行走仍在後續計畫中；未完成的步驟連回官方資料，不填入猜測的參數。</p></header><div className="doc-layout"><aside className="toc" aria-label="本頁目錄"><strong>本頁內容</strong><a href="#version">01 版本與檔案</a><a href="#prepare">02 材料路線</a><a href="#printing">03 列印與試配</a><a href="#assembly">04 組裝方向</a><a href="#power">05 電控與電源</a><a href="#rebuild">06 重建一體件</a><a href="#record">07 留下驗證紀錄</a></aside><article className="doc">
<h2 id="version">01 / 版本與檔案</h2><p>實作目標是 <strong>Open Duck Mini v2</strong>。Microduck 是我們開始這個計畫的靈感來源；請不要混用兩者的材料清單或機構設定。</p><p>本站 CAD 基準為上游 commit <code>b23317a485b3cec7d8417f352478778b3475173c</code>。固定版本，才能讓孔位、圖面與重建結果互相對得上。</p><pre><code>{'git clone https://github.com/apirrone/Open_Duck_Mini.git\ncd Open_Duck_Mini\ngit checkout b23317a485b3cec7d8417f352478778b3475173c'}</code></pre><p><code>print/</code> 是供切片的列印檔；<code>mini_bdx/robots/open_duck_mini_v2/</code> 是本次使用的 CAD／URDF 資料。這兩組資料的座標與尺度不能直接混用。</p>
<h2 id="prepare">02 / 我們採用的材料路線</h2><p>以下是本次建造配置摘要，不是完整採購清單。完整零件與版本，請從<a href="https://github.com/apirrone/Open_Duck_Mini#bom">上游 BOM</a>逐項核對。</p><div className="table-wrap"><table><thead><tr><th>類別</th><th>本次採用</th><th>核對重點</th></tr></thead><tbody><tr><td>關節舵機</td><td>7.4V STS3215 系列，14 顆＋1 備品</td><td>型號、額定電壓、減速比；不混用其他電壓路線</td></tr><tr><td>主控／匯流排</td><td>Pi Zero 2 W、Waveshare Bus Servo Adapter (A)</td><td>板型、驅動、供電及連線辨識</td></tr><tr><td>軸承</td><td>6804ZZ，20 × 32 × 7 mm</td><td>內圈與凸軸、外圈與座孔分別試配</td></tr><tr><td>spacer 嵌件</td><td>M3 × 外徑 4.5 × 長 5 mm</td><td>每件四顆；其他較淺孔另量深度</td></tr><tr><td>列印材料</td><td>PLA；軟腳底用 TPU</td><td>官方基準為 PLA 15%、TPU 40% 填充</td></tr><tr><td>電源／感測</td><td>2S 電池方案、BMS、UBEC、IMU 等</td><td>依實際板型和 BOM 核對；本站電源驗收尚未結案</td></tr></tbody></table></div>
<h2 id="printing">03 / 先試配，再印完整批次</h2><h3>批次 0：三個小零件</h3><ol><li>各印一件 <code>leg_spacer</code>、<code>roll_motor_top</code>、<code>roll_motor_bottom</code>。</li><li>spacer 兩個 Ø4 小孔的兩端各裝一顆嵌件，總共四顆；Ø6 大孔不裝嵌件。</li><li>分別確認 bottom 凸軸與軸承內圈、髖座與舵機的配合。嵌件試配通過，不代表所有髖座孔位都已通過。</li></ol><h3>批次 1：右腿＋右腳，提前加入底座</h3><div className="table-wrap"><table><thead><tr><th>零件</th><th>數量</th><th>材料</th></tr></thead><tbody><tr><td>foot_top、foot_side、foot_bottom_pla</td><td>各 1</td><td>PLA</td></tr><tr><td>foot_bottom_tpu</td><td>1</td><td>TPU</td></tr><tr><td>knee_to_ankle_left_sheet、knee_to_ankle_right_sheet</td><td>各 2</td><td>PLA</td></tr><tr><td>leg_spacer</td><td>2</td><td>PLA</td></tr><tr><td>right_roll_to_pitch、roll_motor_top、roll_motor_bottom</td><td>各 1</td><td>PLA</td></tr><tr><td>trunk_bottom</td><td>1</td><td>PLA</td></tr></tbody></table></div><p>合計 <strong>13 件 PLA＋1 件 TPU</strong>；若不計 trunk_bottom，則為 12 PLA＋1 TPU。批次 0 已合格的零件可計入，不必自動重印。<a href={UP+'docs/print_guide.md'}>官方列印清單 ↗</a></p>
<h2 id="assembly">04 / 裝配前先認方向</h2><div className="notice"><strong>大腿、小腿共用同一組規格，但左右薄板是不同的兩件。</strong><br/>每段各需 left_sheet、right_sheet、spacer 一件。不能把兩片薄板互換，也不能任意翻面。</div><p>右大腿連接 ID 12（髖 pitch）與 ID 13（膝）；右小腿連接 ID 13 與 ID 14（踝）。小腿先接踝舵機線，穿過指定薄板開口，再合上框架。</p><p>右髖部分：ID 10 下方的<strong>主動舵盤</strong>接 roll_motor_top；top 與 bottom 共同支承 ID 11。bottom 的凸軸接軸承內圈，軸承外圈再配合 trunk_bottom。</p><div className="actions"><a className="button primary" href="/assembly.html">開啟互動爆炸圖 ↗</a><a className="button" href={UP+'docs/assembly_guide.md'}>對照官方組裝文件</a></div><p>分解滑桿回到 0% 是 CAD 裝配位置；拉開後的距離只是閱讀間隔，不是加工尺寸或螺絲長度。圖上的零件序號也不是舵機 ID。</p><h3>拆裝後嵌件鬆脫怎麼記錄？</h3><p>先記下是哪個孔、銅嵌件是否連螺絲一起被帶出、孔壁是否變形。照片只能顯示外觀，不能單憑一張照片判定根因。我們此次把 spacer 列為待更換，並另外保留一體件改版。</p>
<h2 id="power">05 / 電控與電源的邊界</h2><p>本次 15 顆舵機電性／位置測試已通過，但第 3–15 顆的人耳異音確認仍未結案。組裝後還要再確認電流與到位，不能直接沿用空載結果。</p><p>電池曾開始充電；充飽結果、輸出接線與 UBEC 量測尚未完成確認。因此本站不把目前的私人接線草稿當成通用教學。請先辨認實際模組端子、極性與額定規格，並保留量測。</p><p>軟體環境請依<a href="https://github.com/apirrone/Open_Duck_Mini_Runtime">官方 Runtime</a>準備。本站尚未完成全機站立／行走驗收，沒有可直接套用的全機調校參數。</p>
<h2 id="rebuild">06 / 重現一體式小腿</h2><p><a href="/downloads/shin-reproduction.zip" download>下載重現包 ZIP</a>，解壓後包含三個原始 CAD 網格、URDF、兩版生成程式、依賴版本與上游授權。從解壓目錄執行：</p><pre><code>{'python3.11 -m venv .venv\n.venv/bin/python -m pip install -r requirements.txt\n.venv/bin/python sim/print/build_shin_unibody.py\n.venv/bin/python sim/print/build_shin_unibody_filled.py'}</code></pre><p>輸出會出現在 <code>designs/right-shin-unibody-v1/</code> 與 <code>v2/</code>，包含 STL、雙視角 PNG 與幾何檢查 JSON。原 CAD 以公尺儲存，程式會轉為毫米；不要額外縮放 1,000 倍。</p><p>v1 將 spacer 兩端各延伸 0.25 mm，連接兩片薄板；v2 再補滿中間固定孔。兩版外形均約 30.70 × 70.65 × 44.85 mm，僅完成 CAD 幾何驗證，還沒通過實物裝入與列印測試。</p>
<h2 id="record">07 / 留下能被接續的紀錄</h2><p>每一步分開記錄「做了什麼」「量到什麼」「還不知道什麼」。別把幾何檢查通過當成承重測試，也別把沒有收到異常回報當成已驗收。</p><div className="actions"><a className="button primary" href="/checklist.html">開啟你的建造 checklist</a><a className="button" href="/downloads/servo-acceptance-log.md">下載本次舵機量測</a></div><p className="meta">公開 checklist 全部從未完成開始。資料只保存在你的瀏覽器，可匯出／匯入 JSON，與我們的建造紀錄分開。</p></article></div></main>}
